CREATE TABLE ACTIONS(
	ACTION_ID INT NOT NULL PRIMARY KEY,
    VALUE  VARCHAR(25) NOT NULL UNIQUE
);


CREATE TABLE ACTIONS_OF_EMPLOYEE(
	EMPLOYEE_ID INT,
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    ACTION_ID INT,
    FOREIGN KEY(ACTION_ID) REFERENCES ACTIONS(ACTION_ID),
    CONSTRAINT ACTIONS_OF_EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID, ACTION_ID)
);
